### ISSUE TITLE
Poor name choice

### ISSUE THREAD

**Issue by ilg-ul** [verseles/xpm#108]
Hi,

Your project name is unfortunate since it clashes with the [xPack Project Manager](https://xpack.github.io/xpm/), an older project, part of the [xPack Project](https://xpack.github.io).

This creates confusion and generates useless support requests, like https://github.com/xpack-dev-tools/riscv-none-elf-gcc-xpack/issues/29#issuecomment-2017220032.

Your project is young, you still have time to change it.

**Comment by insign** [comment]
Hope you change your project name too: https://en.wikipedia.org/wiki/X_PixMap

Focus in your project, good luck.
